/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rjelwuimlbogvhmjelbs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZWx3dWltbGJvZ3ZobWplbGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NzM1MjAsImV4cCI6MjA4MzU0OTUyMH0.qOiKhm4IpjXQGrEPS_AwqbSuit_yAhmusA7NQUs--sA"